language: node_js
cache: yarn
sudo: false
branches:
  except:
  - master
before_deploy:
- rm -rfv dist
- yarn build
deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: mjFLzGTX4cRND/QK45UG+qkfR7iG1PwPgFnHJCfFnmgM034RsWHFK5zV1WNfMwxVvcte9Ru1dO3J9ArLkh5lhp9eFEGp7pTkUQcdX9ed4rkc2UpEFenGfDPiNuzkfOEt36MUQHyiC6cV8aJ1iV1NBQ7CPoiVEGcI49Fs4DkFTh64Wq3Yo0nhgtVk5UTzfk6E0xjM4s9+UbdZdbZ0Y/6j8t0Nxjw5Zptc/vmRALGnXjFCVz8tAHNYb6k/R9DZJoCPCo5V1zZ9tss07DZbzZD3vB/4WvGWB72WCuvi+6sLmrNwvuX+t2ipUgOa7KFinAx/iHDSLhOxnCmyDRcUjfsbPs6pAhx6qy5s3gpqZRzj3rCAqb6vbrgEqNVYbg8+P+TUH4t6DUufLyfY3lBIdPDqJAh8exl4MFCpVarAjxCD3yHltCpjoOz6+o456Ju5+gHpFU709UiawtNlxsc4LFBlTBHGozVVhn90PWedQpa0D21hAFqmZgbAoXT1Tm6gLAl3yuiT7I5KejiLrw7mY/AeQl8XibDogjZ5AkguoUXMfg2uOEQb1Ojz+nSsqQRGhtWEh3hbJ8kRWBJR9K1HPlR3B21gH2B5L/3GCaoM00EjltFBkJuJY937yJ0GeiX/o8wlI+GjNVGMaLGZBmBJJG13foopxO+b0ZhtfHvkZTxDtsE=
  api_key:
    secure: mz9nQ5clttxj+pStmcuiBiPqAZHJzPFaSplax9fAUfdUj6+3BHppkMFvNpp5ereFHZvMPYls7BTxEpQkEaaOB/FZrSUXbrxdika2gW4UjmzKIPue+zdsA7fq7mQ/ncGDLxfQ8KmB19lriBbW8bLjSim9rHmBaxDkq5Ucwa/ZHZ5l/B7WQYCqtUFSJIOje1fNkBRTOssX0LByqPb9o2DSmaOjWhX8E4/b8JrCeBXOXw44Uv6aCsafmi6q4VShpakMRPBFRxWP+7gTiD0am4X6YgYW33nJLS0mNj2OFLm0o6f25o/kgu22pneVus3Srp68eMDYq+C7DXCqFrh8b5W3VQ4i6Biy2PK54K7F5I+BnR8KZ2twbQCCPMlbja6sdpTx/ct/LA7UJIiYWACFusuo6X5DZNgwomcnJwptb8s3sjmJrgyHq9fuKHgQ7QlnToy35QJUG6YXW/F+AFE+hAhie6hR0EJUvfvhQSoqM8sL5Pro1JpJlUGCadaiYMCmS+/3BWKIZiAlpHHLhe2ItBVAJIyhL1DmcrgSVIHffNmgSfvtWzV52fEwtcxggah77VjtMXACNeZ+zkDpLc1adP1WZbBWYJNRgS7EMR0hWvM5ICAxQZ5YOoUJ0tlr80OOZAWCsCpqbTVKJHHxv8ffssW7oSywZs8aqaA5gnTR1hKXfDs=
  on:
    tags: true
    repo: optimizely/react-oui-icons
notifications:
  slack:
    rooms:
    - secure: e6Uwi12kCO4suaESHJtnZgR/P8sautQox80VxHCIxL+M3p00P0yS6d1jQjUcu4V8IB3nGBPKr7WoZR4B+XVwlYR3QbCAZnOpZrF8W4K6oHUwksGFHK0wGmDTQ4QRAyQRXGplShIzG4OQirtgHeyI2aDy9yZ2Mo/EHj6u2oEWIw+eXQEjAlgyLf0FQ0uRb8Z+OpVHvGgbL5+k8K5/bGbuxxQiMahJMuauWDHeWxN2vWEzwsw6nkbNL3lnAYoJIH0AZ6cN/XZ5MHAVm1F+6HvDk2G8gvl0p3/TZFetkjus0vMZBlz1BT1HQQNID6Q4trW12ULOjQrinvxkP8nx9zvH3H2XsSMAqrCMqCs4NuGzHDa0FtIJTd9me3xDHVl48GZtVHJQZbJuUYeVoKhLMcJ5YIlj3Akb3AvSchr1mS4i8TaSRX97rWLxQg5LDd43aGKW9tLdRhWdLyiDm0YunB30DAkhLaJc4Ah6dp7vWdWGZW24r1sR8bwR/F4lbOGQ+NMkL1Gv9mR6vdKfBhjibj0C4rsmTFb4bGMuYhPLeKreMK5K70CAaIhGG3101QyZPd+psV2ZM0sB05GCuSvt1cAIKvny+RAsMq4J9txyjme6bPuejPLoivq7aZMPgUuF4SrJ0yG4FU/x8YLlaoJND64rvcsKSGQKLcHfoSV/EGs7qF4=
    on_success: always
    on_pull_requests: false
