language: node_js
cache: yarn
sudo: false
branches:
  except:
  - master
before_deploy:
- rm -rfv dist
- yarn build
deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: mjFLzGTX4cRND/QK45UG+qkfR7iG1PwPgFnHJCfFnmgM034RsWHFK5zV1WNfMwxVvcte9Ru1dO3J9ArLkh5lhp9eFEGp7pTkUQcdX9ed4rkc2UpEFenGfDPiNuzkfOEt36MUQHyiC6cV8aJ1iV1NBQ7CPoiVEGcI49Fs4DkFTh64Wq3Yo0nhgtVk5UTzfk6E0xjM4s9+UbdZdbZ0Y/6j8t0Nxjw5Zptc/vmRALGnXjFCVz8tAHNYb6k/R9DZJoCPCo5V1zZ9tss07DZbzZD3vB/4WvGWB72WCuvi+6sLmrNwvuX+t2ipUgOa7KFinAx/iHDSLhOxnCmyDRcUjfsbPs6pAhx6qy5s3gpqZRzj3rCAqb6vbrgEqNVYbg8+P+TUH4t6DUufLyfY3lBIdPDqJAh8exl4MFCpVarAjxCD3yHltCpjoOz6+o456Ju5+gHpFU709UiawtNlxsc4LFBlTBHGozVVhn90PWedQpa0D21hAFqmZgbAoXT1Tm6gLAl3yuiT7I5KejiLrw7mY/AeQl8XibDogjZ5AkguoUXMfg2uOEQb1Ojz+nSsqQRGhtWEh3hbJ8kRWBJR9K1HPlR3B21gH2B5L/3GCaoM00EjltFBkJuJY937yJ0GeiX/o8wlI+GjNVGMaLGZBmBJJG13foopxO+b0ZhtfHvkZTxDtsE=
  api_key:
    secure: WEc9Uz1sajQlHW1vMTDL3a6Z86wP/8/zCArwaOUWDa0GyB/dcCSnlB7/RRlj0tt12nYDM+XK/y2vi8pjkgby1aQvdvVM3yPN/mJgnA0J62WuTFr1o+OARkCNv609mYOkI+lLCEh10kvlb+pY0bzY2NR2e8BuBNtoua0EiRj3ripskhdLa6rTn65QWM4qY0aJaYXzugoZwxwSSVgsxxCMLmRxEYcYDVFGYfhn2xifk+rQGtU4vGGi8Ze7/W5C1nwUM/epe7hlGTfFhDIHDtotAeT7/D+IiIXl2DY+4rBOVzqSxjtdRJcHOAbnpQnDAGK57x5iD/uxF/vmpcswEScbBUuv1BWRciop7WOguQ9+tt7nFmZ/tvM/2T1QiQISS4BgjEr/zA3PFLBoaERn3NDXvnooYD3K4cFSpvWtnmxhyt9ZVPwMUjj2+5oCykDMHSbnpvElyEoPzAjxbRQ5BLEBH61BcezG+2SjSuPHOkG7w3wrzMm6RCs/9QkzaVIJHya0lLiauQ0U1m62+VteX0rhQ71ZYHQfmOUxw2nmtk7u5d3guRxzb9HxkUinhR5tStATrWex53tovvADmXWxzxHxItMdBEU8KHchb+iHSvhPJ42UBI44RP5+TWDAmavqFsb5QmRVY3ZlIhTG/kUpWBLuJK2dmDk22EnFRS3Or3z5ZxY=
  on:
    tags: true
    repo: optimizely/react-oui-icons
notifications:
  slack:
    secure: GQRFwvA6qR7b6Hh1fIeWOYnrowtz5I3Pt7eJ6b3wypE2EV4ZP9ARWHYWVKRd+Tm5NpinxWp1/qj+dHYfQrbj7uCqT/WP8mV38U5+37RN0PCpMOBHGzBTG7Rl9QXcWkFWpXXfI02JS2yQBIV1rY9GkSVFyeCI5rHglGVDht461ZBRa7m2Gr6ZqmYG36c+Gl/n3KOnJS59fI7GT/nBzl10RU9Zf2RZnI3il3D3PB2d8DSvDzSgs+Y4QI1Qdzxop8Bu2p/y7OeKuQ7qylgbcyfGn1umXSghWOhQyUzBNlED40xa/biudwbm6cX8sY+2manZd3+Y8ZxM6MONZJFUtIbMarGOZantl/y68Xn/cGwpRFfgf4NL+m/5esjAoeJMMVZ49SGLQyuKqy3Pm/000zM9AEoGHr9Uh6o8d3JHjNsrnPvPRbPJuG/MnwoJU9cxFLIpolOhocMqqQuY2E2ogQk2hUnOnZ+V+knkMNmtPhOD9TYLHy0UhCKRlouHfQGu/bXCS6P4QUMPgJb9v7UuxSpKMkK4aejqXDSjVQyJQqdxI+sX/FUMG3qDujW4QWf8aKKYWL39Gpzhwi6UqcSP6xHJI0OSaY/pmVWwUxvk3QXONZAfuvxEPqw7yQcCQ3q8nclGTccHP3PSGeMVFfxHIyKO7hQNJ/2WZsFKBwwvhl5+8hw=
